# Generated by Django 5.1.2 on 2024-10-13 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopsis', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('clasificacion_rotten', models.IntegerField()),
                ('video_url', models.CharField(max_length=100)),
                ('imagen_pelicula', models.ImageField(blank=True, null=True, upload_to='static/peliculas')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_persona', models.ImageField(blank=True, null=True, upload_to='static/personas')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.IntegerField(choices=[(1, 'Director'), (2, 'Actor')])),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparto', to='cuevana.pelicula')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparto', to='cuevana.persona')),
            ],
        ),
    ]
